// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[5];
h var0[0];
h var0[1];
h var0[2];
h var0[3];
h var0[4];
cx var0[0], var0[1];
rz(1.400000e+00) var0[1];
cx var0[0], var0[1];
cx var0[1], var0[2];
rz(1.400000e+00) var0[2];
cx var0[1], var0[2];
cx var0[2], var0[3];
rz(1.400000e+00) var0[3];
cx var0[2], var0[3];
cx var0[3], var0[4];
rz(1.400000e+00) var0[4];
cx var0[3], var0[4];
rx(6.000000e-01) var0[0];
rx(6.000000e-01) var0[1];
rx(6.000000e-01) var0[2];
rx(6.000000e-01) var0[3];
rx(6.000000e-01) var0[4];
creg var6[5];
measure var0 -> var6;
