// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[1];
h var0[0];
rz(7.853982e-01) var0[0];
rz(1.570796e+00) var0[0];
rz(2.356194e+00) var0[0];
h var0[0];
creg var2[1];
measure var0 -> var2[0];
