// Code generated by NVIDIA's nvq++ compiler
OPENQASM 2.0;

include "qelib1.inc";

qreg var0[1];
rx(1.570796e+00) var0[0];
rx(1.570796e+00) var0[0];
rx(1.570796e+00) var0[0];
rx(1.570796e+00) var0[0];
creg var2[1];
measure var0 -> var2[0];
